<?php
namespace app\admin\controller;

use think\Controller;

class Common extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (empty(session('adminuser'))){
            if (request()->isPost()){
                return json(['code'=>0,"msg"=>"登录过期"]);
            }
            $this->redirect('admin/login/index');
        }
    }
}
