<?php
namespace app\index\controller;

use app\admin\model\LinksModel;
use app\admin\model\SetModel;
use think\Controller;

class Common extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        //取设置
        $setModel = new SetModel();
        $set = $setModel->where('id',1)->find();
        if (!empty($set)){
            $set = unserialize($set['content']);
        }
        else{
            $set = array(
                'title'=>'',
                'keywords'=>'',
                'description'=>'',
                'addresscn'=>'',
                'addressen'=>'',
                'shoplink'=>'',
                'mobile'=>'',
                'icp'=>'',
                'tel'=>'',
            );
        }
        !empty($set['toplogo'])?'':$set['toplogo'] = "";
        !empty($set['bottomlogo'])?'':$set['bottomlogo'] = "";
        !empty($set['qrcode'])?'':$set['qrcode'] = "";
        $this->assign('set',$set);

        //取友情连接
        $linksModel = new LinksModel();
        $links = $linksModel->select();
        $this->assign('links',$links);

        //判断页面
        switch (request()->dispatch()['module'][1]){
            case "index":
                $i = 1;
                break;
            case "banner":
                $i = 2;
                break;
            case "mazhu":
                $i = 3;
                break;
            case "kehu":
                $i = 4;
                break;
            case "news":
                $i = 5;
                break;
            case "my":
                $i = 6;
                break;
            default:
                $i = 1;
                break;
        }
        $this->assign('ispage',$i);
    }
}
